[tools]
python = "3.12"
ffmpeg = "latest"

[phases.setup]
nixPkgs = ["ffmpeg"]

[phases.install]
cmds = [". /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.start]
cmd = ". /opt/venv/bin/activate && export PATH=$PATH:/root/.nix-profile/bin && which ffprobe && python main.py"

