[tools]
python = "3.12"
ffmpeg = "latest"

[phases.setup]
nixPkgs = ["python3", "python3Packages.virtualenv", "ffmpeg"]

[phases.install]
cmds = [
  "python3 --version",
  "python3 -m virtualenv /opt/venv",
  "ls -l /opt",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.start]
cmd = ". /opt/venv/bin/activate && python main.py"
