[tools]
python = "3.12"
ffmpeg = "latest"

[phases.setup]
nixPkgs = ["python3", "ffmpeg"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",        
  "python -m pip install --upgrade pip",   
  "python -m pip install -r requirements.txt"
]

[phases.start]
cmd = "python main.py"
