[tools]
python = "3.12"
ffmpeg = "latest"

[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.start]
cmd = "python main.py"
