[tools]
python = "3.12"
ffmpeg = "latest"

[phases.setup]
nixPkgs = ["python3", "ffmpeg"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.start]
cmd = "python main.py"
